export * from './social';
export * from './wallets';
export * from './chains';
export * from './socialNew';
export { default as iconArrowDown } from './icon-arrow-down.svg';
export { default as iconArrowDownBlue } from './icon-arrow-down-blue.svg';
export { default as iconClose } from './icon-close.svg';
export { default as iconEdit } from './icon-edit.svg';
export { default as iconSettings } from './icon-settings.svg';
export { default as iconSettingsWhite } from './icon-settings-white.svg';
export { default as iconAddBlack } from './icon-add-black.svg';
export { default as iconRemoveBlack } from './icon-remove-black.svg';
export { default as iconAllNFTs } from './icon-all-nfts.svg';
export { default as iconBurn } from './icon-burn.svg';
export { default as iconTransfer } from './icon-transfer.svg';
export { default as iconChange } from './icon-dollar.svg';
export { default as iconRemove } from './icon-remove.svg';
export { default as iconReport } from './icon-report.svg';
export { default as iconLink } from './icon-link.svg';
export { default as iconUpload } from './icon-upload.svg';
export { default as iconCloudUploadBlack } from './icon-cloud-upload-black.svg';
export { default as iconCreateCircle } from './icon-create-circle.svg';
export { default as iconVerifiedMark } from './icon-verified-mark.svg';
export { default as iconCloudUpload } from './icon-cloud-upload.svg';
export { default as iconPropAdd } from './icon-prop-add.svg';
export { default as iconPropRemove } from './icon-prop-delete.svg';
export { default as iconSearch } from './icon-search.svg';
export { ReactComponent as IconSwap } from './icon-arrows-swap.svg';
export { ReactComponent as IconCoin } from './icon-coin.svg';
export { ReactComponent as IconRefresh } from './icon-refresh.svg';
export { ReactComponent as IconEth } from './icon-eth.svg';
export { ReactComponent as IconDashboard } from './icon-dashboard.svg';
export { ReactComponent as IconSettings } from './icon-settings.svg';
export { ReactComponent as IconSettingsWhite } from './icon-settings-white.svg';
export { ReactComponent as IconProfile } from './icon-profile.svg';
export { ReactComponent as IconFolders } from './icon-folders.svg';
export { ReactComponent as IconLogout } from './icon-logout.svg';
export { ReactComponent as IconTriangle } from './icon-triangle-white.svg';
export { ReactComponent as SaleHomePage } from './saleHomePage.svg';
export { ReactComponent as AuthorHomePage } from './authorHomePage.svg';
export { ReactComponent as BookHomePage } from './bookHomePage.svg';
export { ReactComponent as WalletHomePage } from './walletHomePage.svg';
export { ReactComponent as CloudHomePage } from './cloudHomePage.svg';
export { ReactComponent as PenHomePage } from './penHomePage.svg';
export { ReactComponent as PlanetHomePage } from './planetHomePage.svg';
