import { profilePic, smallArtCardImage } from 'assets/img';

export const data = [
  {
    id: 1,
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    id: 2,
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    id: 3,
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    id: 4,
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    id: 5,
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    id: 6,
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    id: 7,
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    id: 8,
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
];
