export { default as Home } from './Home';
export { default as Discover } from './Discover';
export { default as DetailArtwork } from './Detail/Artwork';
export { default as DetailAuction } from './Detail/Auction';
export { default as ProfileEdit } from './ProfileEdit';
export { default as ProfilePage } from './ProfilePage';
export { default as Activity } from './Activity';
export { default as CreateToken } from './CreateToken';
export { default as UploadVariants } from './UploadVariants';
