import {
  mediumArtCardSecondary1,
  mediumArtCardSecondary2,
  mediumArtCardSecondary3,
  profilePic,
  smallArtCardImage,
} from 'assets/img';

export const data = [
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured', 'rare'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured', 'rare'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured', 'rare'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured', 'rare'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured'],
  },
];

export const dataMediumCards = [
  {
    image: smallArtCardImage,
    imageSecondary1: mediumArtCardSecondary1,
    imageSecondary2: mediumArtCardSecondary2,
    imageSecondary3: mediumArtCardSecondary3,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    image: smallArtCardImage,
    imageSecondary1: mediumArtCardSecondary1,
    imageSecondary2: mediumArtCardSecondary2,
    imageSecondary3: mediumArtCardSecondary3,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    image: smallArtCardImage,
    imageSecondary1: mediumArtCardSecondary1,
    imageSecondary2: mediumArtCardSecondary2,
    imageSecondary3: mediumArtCardSecondary3,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
];
