import { profilePic, smallArtCardImage } from 'assets/img';

export const data = [
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
  },
];
