import { hotAuctionTest, profilePic } from 'assets/img';

export const data = [
  {
    title: 'The Lifelines',
    author: 'Max Aarons',
    authorPic: profilePic,
    artPic: hotAuctionTest,
    body: "When I open my eyes and see the lines that live on the life I left behind, I feel disconnected from the place that I call home When I try to rewind, I can't design a way to go back to that place and time I remember that moment that changed everything I know",
    tags: ['netify', 'rare', 'art'],
    views: 10000,
    likes: 1000,
    currentPrice: 0,
    priceAsset: 'eth',
    auctionEndingTime: '14.45',
    bidders: [
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
    ],
  },
  {
    title: 'The Lifelines',
    author: 'Max Aarons',
    authorPic: profilePic,
    artPic: hotAuctionTest,
    body: "When I open my eyes and see the lines that live on the life I left behind, I feel disconnected from the place that I call home When I try to rewind, I can't design a way to go back to that place and time I remember that moment that changed everything I know",
    tags: ['netify', 'rare', 'art'],
    views: 10000,
    likes: 1000,
    currentPrice: 0,
    priceAsset: 'eth',
    auctionEndingTime: '14.45',
    bidders: [
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
    ],
  },
  {
    title: 'The Lifelines',
    author: 'Max Aarons',
    authorPic: profilePic,
    artPic: hotAuctionTest,
    body: "When I open my eyes and see the lines that live on the life I left behind, I feel disconnected from the place that I call home When I try to rewind, I can't design a way to go back to that place and time I remember that moment that changed everything I know",
    tags: ['netify', 'rare', 'art'],
    views: 10000,
    likes: 1000,
    currentPrice: 0,
    priceAsset: 'eth',
    auctionEndingTime: '14.45',
    bidders: [
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
    ],
  },
  {
    title: 'The Lifelines',
    author: 'Max Aarons',
    authorPic: profilePic,
    artPic: hotAuctionTest,
    body: "When I open my eyes and see the lines that live on the life I left behind, I feel disconnected from the place that I call home When I try to rewind, I can't design a way to go back to that place and time I remember that moment that changed everything I know",
    tags: ['netify', 'rare', 'art'],
    views: 10000,
    likes: 1000,
    currentPrice: 0,
    priceAsset: 'eth',
    auctionEndingTime: '14.45',
    bidders: [
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
    ],
  },
  {
    title: 'The Lifelines',
    author: 'Max Aarons',
    authorPic: profilePic,
    artPic: hotAuctionTest,
    body: "When I open my eyes and see the lines that live on the life I left behind, I feel disconnected from the place that I call home When I try to rewind, I can't design a way to go back to that place and time I remember that moment that changed everything I know",
    tags: ['netify', 'rare', 'art'],
    views: 10000,
    likes: 1000,
    currentPrice: 0,
    priceAsset: 'eth',
    auctionEndingTime: '14.45',
    bidders: [
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
    ],
  },
  {
    title: 'The Lifelines',
    author: 'Max Aarons',
    authorPic: profilePic,
    artPic: hotAuctionTest,
    body: "When I open my eyes and see the lines that live on the life I left behind, I feel disconnected from the place that I call home When I try to rewind, I can't design a way to go back to that place and time I remember that moment that changed everything I know",
    tags: ['netify', 'rare', 'art'],
    views: 10000,
    likes: 1000,
    currentPrice: 0,
    priceAsset: 'eth',
    auctionEndingTime: '14.45',
    bidders: [
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
      {
        avatar: profilePic,
        name: '@JorgeLRZ',
        bid: '1.00',
        bidAsset: 'eth',
      },
    ],
  },
];
