import { profilePic, smallArtCardImage } from "assets/img";

export const data = [
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured', 'rare'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured', 'rare'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured', 'rare'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured', 'rare'],
  },
  {
    image: smallArtCardImage,
    name: 'Waves on chain',
    price: '2.00',
    asset: 'eth',
    inStockNumber: '7',
    author: 'Gremmy Thoumeaux',
    authorAvatar: profilePic,
    likesNumber: 3500,
    tags: ['featured'],
  },
];
